from sre_constants import REPEAT
from nonebot.default_config import *

NICKNAME = ['软白','!']
COMMAND_START = ['']
PORT = 9222
DEBUG = 1
SUPERUSERS = 1320265781
DELETE_TIME = 60
HDELETET_TIME = 10
BLACKLIST = {}
WHITEGROUPLIST = {}
#R18LIST = {}
SESSION_RUNNING_EXPRESSION = ''
REPEAT_TIME = 3



